services:
  postgres:
    image: postgres:16
    container_name: sql-ex-postgres
    environment:
      POSTGRES_DB: sql_ex
      POSTGRES_USER: sql_ex
      POSTGRES_PASSWORD: sql_ex
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-init.db:/docker-entrypoint-initdb.d:ro
      - ./data:/data:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sql_ex -d sql_ex"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
